// <auto-generated />
using System;
using LivingWorld.Infrastructure;
using LivingWorld.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivingWorld.Infrastructure.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260806001431_AddPeriodTemplates")]
    partial class AddPeriodTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LivingWorld.Infrastructure.EventLogRecord", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId", "Tick", "Sequence");

                    b.HasIndex("BranchId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("LivingWorld.Infrastructure.FactLogRecord", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationCityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Significance")
                        .HasColumnType("REAL");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.HasKey("BranchId", "FactId");

                    b.HasIndex("BranchId");

                    b.ToTable("FactLog");
                });

            modelBuilder.Entity("LivingWorld.Infrastructure.PeriodTemplateRecord", b =>
                {
                    b.Property<string>("PeriodId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PeriodId", "Version");

                    b.HasIndex("PeriodId");

                    b.ToTable("PeriodTemplates");
                });

            modelBuilder.Entity("LivingWorld.Infrastructure.WorldSnapshotRecord", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolatileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId", "Tick");

                    b.HasIndex("BranchId");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
