// <auto-generated />
using LivingWorld.Infrastructure;
using LivingWorld.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivingWorld.Infrastructure.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20260727021043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LivingWorld.Infrastructure.EventLogRecord", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId", "Tick", "Sequence");

                    b.HasIndex("BranchId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("LivingWorld.Infrastructure.WorldSnapshotRecord", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolatileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId", "Tick");

                    b.HasIndex("BranchId");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
